repositories {
    maven {
        name = "skaggsm"
        url = uri("https://maven.skaggsm.com/releases")
    }
}

dependencies {
    implementation("com.skaggsm:java-mumble-link:${java_mumble_link_version}") {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
        exclude group: 'net.java.dev.jna'
    }

    jarJar(implementation("com.skaggsm:java-mumble-link:${java_mumble_link_version}")) {
        version {
            strictly "[${java_mumble_link_version},)"
            prefer "${java_mumble_link_version}"
        }
    }
    jarJar(implementation("com.skaggsm:jvm-shared-memory:0.2.7")) {
        version {
            strictly "[0.2.7,)"
            prefer "0.2.7"
        }
    }
}
